#pragma once

#define DEFINES_H
#define BOARDSIZE 5
#define PLAYERS 2
#define STUDENTS 4
#define MASTER 1
enum E_PLAYERCOLOR { red, blue };
enum E_PIECETYPE { master, student };

#define TILESIZE 100
#define SIDEPANELWIDTH 250
#define CARDPANELHEIGHT 150
#define TILEPADDING 10
#define WINDOWLENGTHSIZE CARDPANELHEIGHT * 2 + TILESIZE * BOARDSIZE + 2 * TILEPADDING + (BOARDSIZE - 1) * TILEPADDING
#define WINDOWWIDTHSIZE SIDEPANELWIDTH * 2 + TILESIZE * BOARDSIZE + 2 * TILEPADDING + (BOARDSIZE - 1) * TILEPADDING
