#pragma once

#define DEFINES_H
#define BOARDSIZE 5

#define TILESIZE 100
#define SIDEPANELWIDTH 250
#define CARDPANELHEIGHT 150
#define TILEPADDING 10
#define WINDOWLENGTHSIZE CARDPANELHEIGHT * 2 + TILESIZE * BOARDSIZE + 2 * TILEPADDING + (BOARDSIZE - 1) * TILEPADDING
#define WINDOWWIDTHSIZE SIDEPANELWIDTH * 2 + TILESIZE * BOARDSIZE + 2 * TILEPADDING + (BOARDSIZE - 1) * TILEPADDING
